services:
  - type: web
    name: disease-predictor
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: cd Website && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
